heater_queue:  tcp://127.0.0.1:9909
thermo_queue:  tcp://127.0.0.1:9908
report_url: http://192.168.0.100/brewing/in?
thermometer_binary: '/home/richc/pcsensor/pcsensor -s'

pid:
  p: 0.2
  i: 0.05
  d: -0.05

thermometers: 
  mash:
    id: 28-000004672ef9
    correct: -0.5
  herms:
    id: 28-00000467bc19
    correct: 0
  flow:
    id: 28-0000047f4a80
    correct: -1
